weather:
    enabled: True
    key: # YOUR KEY HERE
    latitude: 50.5668102
    longitude: 4.7160152
    units: ca
quote:
    enabled: True
    url: http://www.brainyquote.com/quotes_of_the_day.html
fact:
    enabled: True
    url: http://facts.randomhistory.com/
system:
    enabled: True
    elements:
        battery: True
        home: True